from nautobot.extras.plugins import register_custom_validators
from .data_compliance_rules import DeviceDataComplianceRules, RackDeviceComplianceRules


register_custom_validators(DeviceDataComplianceRules, RackDeviceComplianceRules)
